const objects = {
  // Houses & Buildings
  H1: require('../../assets/objects/7House/1.png'),
  H2: require('../../assets/objects/7House/2.png'),
  H3: require('../../assets/objects/7House/3.png'),
  H4: require('../../assets/objects/7House/4.png'),
  H5: require('../../assets/objects/7House/5.png'),
  H6: require('../../assets/objects/7House/6.png'),
  TO1: require('../../assets/archer_tower.png'),
  TO2: require('../../assets/cannon_tower.png'),
  TO3: require('../../assets/mage_tower.png'),

  FLO1: require('../../assets/objects/Flower/1.png'),
  FLO2: require('../../assets/objects/Flower/2.png'),
  FLO3: require('../../assets/objects/Flower/3.png'),
  FLO4: require('../../assets/objects/Flower/4.png'),
  FLO5: require('../../assets/objects/Flower/5.png'),
  FLO6: require('../../assets/objects/Flower/6.png'),
  FLO7: require('../../assets/objects/Flower/7.png'),
  FLO8: require('../../assets/objects/Flower/8.png'),
  FLO9: require('../../assets/objects/Flower/9.png'),
  FLO10: require('../../assets/objects/Flower/10.png'),
  FLO11: require('../../assets/objects/Flower/11.png'),
  FLO12: require('../../assets/objects/Flower/12.png'),

  P1: require('../../assets/objects/Pointer/1.png'),
  P2: require('../../assets/objects/Pointer/2.png'),
  P3: require('../../assets/objects/Pointer/3.png'),
  P4: require('../../assets/objects/Pointer/4.png'),
  P5: require('../../assets/objects/Pointer/5.png'),
  P6: require('../../assets/objects/Pointer/6.png'),

  FL1: require('../../assets/objects/Flag/1.png'),
  FL2: require('../../assets/objects/Flag/2.png'),
  // Decorations
  F1: require('../../assets/objects/Fence/1.png'),
  F2: require('../../assets/objects/Fence/2.png'),
  F3: require('../../assets/objects/Fence/3.png'),
  F4: require('../../assets/objects/Fence/4.png'),
  F5: require('../../assets/objects/Fence/5.png'),
  F6: require('../../assets/objects/Fence/6.png'),
  F7: require('../../assets/objects/Fence/7.png'),
  F8: require('../../assets/objects/Fence/8.png'),
  F9: require('../../assets/objects/Fence/9.png'),
  F10: require('../../assets/objects/Fence/10.png'),
  FI1: require('../../assets/objects/Campfire/1.png'),
  FI2: require('../../assets/objects/Campfire/2.png'),

  C1: require('../../assets/objects/Camp/1.png'),
  C2: require('../../assets/objects/Camp/2.png'),
  C3: require('../../assets/objects/Camp/3.png'),
  C4: require('../../assets/objects/Camp/4.png'),
  C5: require('../../assets/objects/Camp/5.png'),
  C6: require('../../assets/objects/Camp/6.png'),

  BU1: require('../../assets/objects/Bush/1.png'),
  BU2: require('../../assets/objects/Bush/2.png'),
  BU3: require('../../assets/objects/Bush/3.png'),
  BU4: require('../../assets/objects/Bush/4.png'),
  BU5: require('../../assets/objects/Bush/5.png'),
  BU6: require('../../assets/objects/Bush/6.png'),
  BU7: require('../../assets/objects/Bush/Tree1.png'),
  BU8: require('../../assets/objects/Bush/Tree2.png'),
  BU9: require('../../assets/objects/Bush/Log1.png'),
  BU10: require('../../assets/objects/Bush/Log2.png'),
  BU11: require('../../assets/objects/Bush/Log3.png'),
  BU12: require('../../assets/objects/Bush/Log4.png'),


  // Doors
  D1: require('../../assets/objects/Door1.png'),
  D2: require('../../assets/objects/Door2.png'),
  DD1: require('../../assets/objects/DoubleDoor1.png'),
  DD2: require('../../assets/objects/DoubleDoor2.png'),

  // Towers
  P7: require('../../assets/objects/PlaceForTower1.png'),
  P8: require('../../assets/objects/PlaceForTower2.png'),
  TE1: require('../../assets/objects/6Tent/1.png'),
  TE2: require('../../assets/objects/6Tent/2.png'),
  TE3: require('../../assets/objects/6Tent/3.png'),
  TE4: require('../../assets/objects/6Tent/4.png'),

  // Shadows
  S1: require('../../assets/objects/1Shadow/1.png'),
  S2: require('../../assets/objects/1Shadow/2.png'),
  S3: require('../../assets/objects/1Shadow/3.png'),
  S4: require('../../assets/objects/1Shadow/4.png'),
  S5: require('../../assets/objects/1Shadow/5.png'),
  S6: require('../../assets/objects/1Shadow/6.png'),

  // Stones
  ST1: require('../../assets/objects/2Stone/1.png'),
  ST2: require('../../assets/objects/2Stone/2.png'),
  ST3: require('../../assets/objects/2Stone/3.png'),
  ST4: require('../../assets/objects/2Stone/4.png'),
  ST5: require('../../assets/objects/2Stone/5.png'),
  ST6: require('../../assets/objects/2Stone/6.png'),

  // Decorations
  D1: require('../../assets/objects/3Decor/1.png'),
  D2: require('../../assets/objects/3Decor/2.png'),
  D3: require('../../assets/objects/3Decor/3.png'),
  D4: require('../../assets/objects/3Decor/4.png'),
  D5: require('../../assets/objects/3Decor/5.png'),
  D6: require('../../assets/objects/3Decor/6.png'),
  D7: require('../../assets/objects/3Decor/7.png'),
  D8: require('../../assets/objects/3Decor/8.png'),
  D9: require('../../assets/objects/3Decor/9.png'),
  D10: require('../../assets/objects/3Decor/10.png'),
  D11: require('../../assets/objects/3Decor/11.png'),
  D12: require('../../assets/objects/3Decor/12.png'),
  D13: require('../../assets/objects/3Decor/13.png'),
  D14: require('../../assets/objects/3Decor/14.png'),
  D15: require('../../assets/objects/3Decor/15.png'),
  D16: require('../../assets/objects/3Decor/16.png'),
  D17: require('../../assets/objects/3Decor/17.png'),

  // Boxes
  B1: require('../../assets/objects/4Box/1.png'),
  B2: require('../../assets/objects/4Box/2.png'),
  B3: require('../../assets/objects/4Box/3.png'),
  B4: require('../../assets/objects/4Box/4.png'),
  B5: require('../../assets/objects/4Box/5.png'),

  // Grass
  G1: require('../../assets/objects/5Grass/1.png'),
  G2: require('../../assets/objects/5Grass/2.png'),
  G3: require('../../assets/objects/5Grass/3.png'),
  G4: require('../../assets/objects/5Grass/4.png'),
  G5: require('../../assets/objects/5Grass/5.png'),
  G6: require('../../assets/objects/5Grass/6.png'),

  
  T1: require('../../assets/tiles/Tile2_01.png'),
  T2: require('../../assets/tiles/Tile2_02.png'),
  T3: require('../../assets/tiles/Tile2_03.png'),
  T4: require('../../assets/tiles/Tile2_04.png'),
  T5: require('../../assets/tiles/Tile2_05.png'),
  T6: require('../../assets/tiles/Tile2_06.png'),
  T7: require('../../assets/tiles/Tile2_07.png'),
  T8: require('../../assets/tiles/Tile2_08.png'),
  T9: require('../../assets/tiles/Tile2_09.png'),
  T10: require('../../assets/tiles/Tile2_10.png'),
  T11: require('../../assets/tiles/Tile2_11.png'),
  T12: require('../../assets/tiles/Tile2_12.png'),
  T13: require('../../assets/tiles/Tile2_13.png'),
  T14: require('../../assets/tiles/Tile2_14.png'),
  T15: require('../../assets/tiles/Tile2_15.png'),
  T16: require('../../assets/tiles/Tile2_16.png'),
  T17: require('../../assets/tiles/Tile2_17.png'),
  T18: require('../../assets/tiles/Tile2_18.png'),
  T19: require('../../assets/tiles/Tile2_19.png'),
  T20: require('../../assets/tiles/Tile2_20.png'),
  T21: require('../../assets/tiles/Tile2_21.png'),
  T22: require('../../assets/tiles/Tile2_22.png'),
  T23: require('../../assets/tiles/Tile2_23.png'),
  T24: require('../../assets/tiles/Tile2_24.png'),
  T25: require('../../assets/tiles/Tile2_25.png'),
  T26: require('../../assets/tiles/Tile2_26.png'),
  T27: require('../../assets/tiles/Tile2_27.png'),
  T28: require('../../assets/tiles/Tile2_28.png'),
  T29: require('../../assets/tiles/Tile2_29.png'),
  T30: require('../../assets/tiles/Tile2_30.png'),
  T31: require('../../assets/tiles/Tile2_31.png'),
  T32: require('../../assets/tiles/Tile2_32.png'),
  T33: require('../../assets/tiles/Tile2_33.png'),
  T34: require('../../assets/tiles/Tile2_34.png'),
  T35: require('../../assets/tiles/Tile2_35.png'),
  T36: require('../../assets/tiles/Tile2_36.png'),
  T37: require('../../assets/tiles/Tile2_37.png'),
  T38: require('../../assets/tiles/Tile2_38.png'),
  T39: require('../../assets/tiles/Tile2_39.png'),
  T40: require('../../assets/tiles/Tile2_40.png'),
  T41: require('../../assets/tiles/Tile2_41.png'),
  T42: require('../../assets/tiles/Tile2_42.png'),
  T43: require('../../assets/tiles/Tile2_43.png'),
  T44: require('../../assets/tiles/Tile2_44.png'),
  T45: require('../../assets/tiles/Tile2_45.png'),
  T46: require('../../assets/tiles/Tile2_46.png'),
  T47: require('../../assets/tiles/Tile2_47.png'),
  T48: require('../../assets/tiles/Tile2_48.png'),
  T49: require('../../assets/tiles/Tile2_49.png'),
  T50: require('../../assets/tiles/Tile2_50.png'),
  T51: require('../../assets/tiles/Tile2_51.png'),
  T52: require('../../assets/tiles/Tile2_52.png'),
  T53: require('../../assets/tiles/Tile2_53.png'),
  T54: require('../../assets/tiles/Tile2_54.png'),
  T55: require('../../assets/tiles/Tile2_55.png'),
  T56: require('../../assets/tiles/Tile2_56.png'),
  T57: require('../../assets/tiles/Tile2_57.png'),
  T58: require('../../assets/tiles/Tile2_58.png'),
  T59: require('../../assets/tiles/Tile2_59.png'),
  T60: require('../../assets/tiles/Tile2_60.png'),
  T61: require('../../assets/tiles/Tile2_61.png'),
  T62: require('../../assets/tiles/Tile2_62.png'),
  T63: require('../../assets/tiles/Tile2_63.png'),
  T64: require('../../assets/tiles/Tile2_64.png'),
};

export default objects;